name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  golang:
    name: Golang
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.54

  container:
    name: Containerfile
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Containerfile
