name: Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BINARY_NAME: koherence

jobs:
  golang:
    name: Golang
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.2'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt install -yq --no-install-recommends make

      - name: Build
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
        run: make build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BINARY_NAME }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: ${{ env.BINARY_NAME }}
          if-no-files-found: error

  container:
    name: Containerfile
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: ${{ matrix.platform }}/${{ matrix.arch }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

  release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - golang
      - container
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Upload release
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sha256sum ${{ env.BINARY_NAME }}-* | sed 's| .*/|  |' > sha256sum.txt
          gh release create "$TAG_NAME" --draft --title "${{ env.BINARY_NAME }} ${TAG_NAME#jq-}" --generate-notes
          gh release upload "$TAG_NAME" --clobber ${{ env.BINARY_NAME }}-* sha256sum.txt
